### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by SerjDSA**
[DEMO LINK](https://serjdsa.github.io/Museum/)

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great start! Consider fixing validation errors 
Screenshot 2023-12-01 at 14 40 49
Screenshot 2023-12-01 at 14 40 54
Screenshot 2023-12-01 at 14 41 31
The backdrop should span the entire screen 
Screenshot 2023-12-01 at 14 41 46
Consider using transitions to avoid links jumping on hover 
Screenshot 2023-12-01 at 14 41 57
The entire button should be clickable 
Screenshot 2023-12-01 at 14 42 36
* Consider adding the required attribute here
* Consider fixing autocomplete bluish background on autocomplete
* Consider removing the default outline 
Screenshot 2023-12-01 at 14 42 48
Check margins here 
Screenshot 2023-12-01 at 14 45 20
Screenshot 2023-12-01 at 14 45 29
Check the layout here with Figma 
Screenshot 2023-12-01 at 14 45 41
Screenshot 2023-12-01 at 14 45 46
Consider fixing alignment here 
Screenshot 2023-12-01 at 14 46 32
This link shouldn't open the menu. It's an anchor link to the contacts section

**Review by SerjDSA — COMMENTED** [review]
[DEMO LINK](https://serjdsa.github.io/Museum/)

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Maybe you forgot to deploy changes, as nothing has changed

**Review by SerjDSA — COMMENTED** [review]
[DEMO LINK](https://serjdsa.github.io/Museum/)

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
You need to deploy changes. Nothing has changed since my last review

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. update year 
image
2. horizontal scroll
image
3. Add some intends 
image

**Review by SerjDSA — COMMENTED** [review]
[DEMO LINK](https://serjdsa.github.io/Museum/)

**Pull request closed without merging**
