### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DariaSlayer**
[DEMO LINK](https://DariaSlayer.github.io/Museum/)

### CODE REVIEW

**Comment by DariaSlayer** [comment]
sorry, I checked the file. but I don't see where I have more than 2 attributes per line

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Good job! Let's improve it
- use container to limit the max-width of content with 1280px
image

- compare your layout with the mockup
image
image

- add this element
image

- here should be some space under the input
image

- all contacts should be links
image

- fix this behavior
image

- make the background darker when the menu is opened
- place these links as in the mockup and add hover effects to them
image
image

- make the menu appear smoothly
- check the button sizes
image

- there should be a slider in the gallery section on a tab and mobile screens. You can implement a slider later when you learn JS, but make this section look like in the mockup
- center the text in the button (phone)
image

**Comment by DariaSlayer** [comment]
hello. I fixed all except for header image cause I have no idea how to position that background image and its sizes so it fits all devices (I was told to kinda pixel guess it but it doesn't work). will be really grateful if you could help me with the solution for it since I can't get a proper answer on how to solve it. thank you

**Comment by DariaSlayer** [comment]
tried to fix it all. hope it works

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Good job! Let's improve your code a bit)
1. please center your container 
image
2. but your menu must be covered all screen 
image
3.  remove autofill styles
image
4. button sticky to side
image

**Comment by DariaSlayer** [comment]
I was told by mentor in mate academy chat to remove limited width of the page, so I will remove it

**Comment by DariaSlayer** [comment]
I tried to fix autofill styles using link and info mentor provided me with but it still doesn't work. so I don't know how to fix it

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Looks much better but check these points please
1. try to add these styles
image
2. https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ 
it will help you to remove autocomlete styles

**Review by denys-danyliuk — APPROVED** [review]
would be cool to add links to real NAMU accounts, I believe they have them in instagram and facebook, search for it
Знімок екрана 2023-09-04 о 21 07 30

open menu smoothly
Знімок екрана 2023-09-04 о 21 08 12

delete outline and this blue line after autocomplete
Знімок екрана 2023-09-04 о 21 09 06

**Comment by DariaSlayer** [comment]
sure! I'll fix it when I will be back with js skills to add gallery slider! I promise. thank you

**Pull request closed without merging**
