### PR TITLE
add first part

### PR DESCRIPTION
**Pull request by mishakoshilka**
https://mishakoshilka.github.io/Museum/

### CODE REVIEW

**Review by Andriy-Shymkiv — CHANGES_REQUESTED** [review]
good job, keep going!

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
You need to check all sections as per the design and correct it yourself

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Add favicon and actual title
image

2. Add hover effects for all clickable elements and buttons
image

3. The color of the button is not the same as in the design
Demo
image

Design
image

4. The image should stretch to the full width on the right
Demo
image

Design
image

5. Need to fix the wrap as on the design
Demo
image

Design
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Looks really nice! I suggest to fix validation errors 
Screenshot 2023-09-29 at 14 00 27
Screenshot 2023-09-29 at 14 01 16
The menu should have the width of the full-screen size 
Screenshot 2023-09-29 at 14 03 06
Sections overlaping should be fixed 
Screenshot 2023-09-29 at 14 05 19
Screenshot 2023-09-29 at 14 05 29
Add hovers for interactive elements

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Almost done: 
Screenshot 2023-09-29 at 15 52 06
There are a few validation errors 
Screenshot 2023-09-29 at 15 55 38

Sections overlap a bit on tablets

**Review by maxim2310 — CHANGES_REQUESTED** [review]
please check out why button is not working 
image

**Review by nazarmatsevych — APPROVED** [review]
Well done!

**Pull request closed without merging**
