### PR TITLE
NAMU landing page

### PR DESCRIPTION
**Pull request by maksym-kostetskyi**
https://maksym-kostetskyi.github.io/Museum/

I am not sure why but when deployed to github pages its not gettin darkened when menu pop up, and when opening project locally with npm start it works fine, also same with gallery scroll - i implemented scrolling using js and if works for both tablets and mobile but after deploying its not working on github pages, could you help what can he wrong? Screenshots attached
Знімок екрана 2023-08-16 175136
Знімок екрана 2023-08-16 175241
Знімок екрана 2023-08-16 175247

### CODE REVIEW

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good work! Lets improve it

1. menu should have full screen width and and the page should be darkened
image

2.add hover effects on buttons 
image
image

3.remove target="_blank" from phones 
image

4.not needed to redirect on real `namu` on logo click 
image

5. looks weird on mobile too
image

**Comment by TarasHoliuk** [comment]
1. Now, the menu doesn't appear after the burger button click:
image

2. Add transition for links hover effect:
image

3. It might be just an anchor link (but I guess not critical here - up to you):
image

4. Doesn't match design:
image
image

The same here - paddings are too big or redundant:
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Keep going!
Some fixes still required
Feel free to ask in the chat if you need help with the menu implementation

**Comment by maksym-kostetskyi** [comment]
I have an issue with git hub pages not showing the correct version of the website - locally it is working fine, the menu works, and the gallery dots change slides (implemented using JS), here's the link to the video https://www.veed.io/view/541f68e8-fc42-402c-9613-a27ea2b3e6b9?panel=share, I might have uploaded something in the wrong way or that is some issue with Github, though I have committed all changes, pushed everything to develop and deployed it to GitHub, could you look the video, I can't get why it's not showing the correct version of the website here.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
if you have some problems, please, feel free to ask in the chat

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Well done! But slider still not working :( 
Text in your `fe_chat` about issue and mentors will help you to fix  it

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Slider still not work.
Maybe try to deploy again.
If you have any questions - feel free to ask in fe_chat.

**Comment by maksym-kostetskyi** [comment]
it works as intended on my side, also checked it on my phone, link for videoproof is below, please check once more
https://github.com/mate-academy/Museum/assets/93444537/8e7dd229-28fb-4737-b56f-38996f030b1f

**Review by OleziO — APPROVED** [review]

**Pull request closed without merging**
