### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KaterynaEV**
- [DEMO LINK](https://KaterynaEV.github.io/Museum/)

Don't know how to scroll gallery on mobile and tablet

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. must be the links
image

2. I cannot close the menu

3. looks strange
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! There are just a few issues to fix: 
Screenshot 2023-11-05 at 15 53 34
Some sections overlap the menu while scrolling 
Screenshot 2023-11-05 at 15 53 08
Screenshot 2023-11-05 at 15 53 16
This section layout doesn't match the Figma design 
Screenshot 2023-11-05 at 15 51 24
Links overlap on tablet

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great progress here! Consider fixing the previous review comments: 
Screenshot 2023-11-05 at 18 43 11
Screenshot 2023-11-05 at 18 43 18
1) Center the block 2) Avoid overlapping

**Review by volodymyr-soltys97 — APPROVED** [review]
Good job 👍

**Pull request closed without merging**
