### PR TITLE
-+

### PR DESCRIPTION
**Pull request by Fugas252mm**
[DEMO LINK](https://Fugas252mm.github.io/Museum/).

### CODE REVIEW

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Good job! Submit new pull request when you will end task to the end!

**Comment by Fugas252mm** [comment]
Sorry, I put it up for review to keep the lights on. I spent a lot of time creating the side menu, it's a shame not to get a flame today.

**Review by etojeDenys — CHANGES_REQUESTED** [review]
still cannot open the menu section on menu burger button click,

feel free to ask for some help in the chat with that

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Keep going

**Comment by Fugas252mm** [comment]
Is there any way to improve the "events" section?

**Review by etojeDenys — CHANGES_REQUESTED** [review]
feel free to ask for some help in the chat

1. 
image

image


2.
image

3. 
image

4. looks different
image
image

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Waiting other sections.

**Pull request closed without merging**
