### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dimarogkov**
[DEMO LINK](https://dimarogkov.github.io/Museum/)

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. Need to remove autocomplete styles
image

2. Add transition for these hover effects
image

3. When clicking on these elements, the page turns white for a while, this needs to be fixed, and social network icons should also lead to the relevant social networks
image
image

**Comment by dimarogkov** [comment]
1) Need to remove autocomplete styles - I don't have them
3) After clicking, the page turns white because I have a loader. It is a white wrapper that shows for some time when the page is loaded.

**Review by loralevitska — CHANGES_REQUESTED** [review]
1. I don't have them - make some saved login and password in your browser and you will see. Please fix this 
2. After clicking, the page turns white because I have a loader. It is a white wrapper that shows for some time when the page is loaded. - ok, then add colorful loader, maybe green? according main page color. it doesn't look good when you just see a white screen, the user doesn't understand what's happening at that moment. Also imagine that the user has a slow Internet and your loader works for 5-6 seconds, the user will leave such a site and think that the page has fallen... it is worth showing the user the [loading process](https://www.w3schools.com/howto/howto_css_loader.asp)

3. make it link and add hover effect
image

4. add anchors to appropriate part of page
image

If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

**Review by etojeDenys — CHANGES_REQUESTED** [review]
add anchors to the appropriate part of page also here
image

**Review by loralevitska — APPROVED** [review]
Almost perfect) Check my comment for improvement

- open this link in new tab use google maps (appropriate address)
image

**Pull request closed without merging**
