### PR TITLE
'draft'

### PR DESCRIPTION
**Pull request by Hanna-Balabukha**
https://Hanna-Balabukha.github.io/Museum/

### CODE REVIEW

**Review by polosanya — CHANGES_REQUESTED** [review]
Nice start!
1. Favicon doesn't look good. Try to set another one
image
2. Background color doesn't match the design. Also, it would be great for main screen to take the whole height
image
image
3. It would be great to add some hover effect to this button and make all its area clickable with cursor pointer
image
4. Cursor shouldn't completely disappear on this text hover
image
5. The clickable area of burger menu icon is wrong
burger-menu

**Review by anstsot — CHANGES_REQUESTED** [review]
1. the grayish background should added once the menu is opened
image

2. some of the text should be bold and some - normal
image

3. the gallery on bigger screen doesn't match the design
image

4. fit the button styles
image

5. add hover on social icons and fix the text on the right side (it's invisible on the top)
image

6. the slider isn't working
image

7. fix footer on smaller device
image

**Review by agniya-i — CHANGES_REQUESTED** [review]
1. Add cursor pointer to form button 

Screenshot 2023-05-14 at 13 04 16

2. Contacts block doesn't match the design  

Screenshot 2023-05-14 at 13 04 55

Also, there should be the ability to click on phone, email and address, not only open a map by clicking on the whole block 

3. Fix Instagram icon, you can upload the icon with a circle choosing the whole frame in Figma
Screenshot 2023-05-14 at 12 59 58

**Review by anstsot — CHANGES_REQUESTED** [review]
Not all previous comments were fixed. Please review all of them and fix accordingly.
Add hover effects to all needed elements as well. Here is the [checklist](https://github.com/mate-academy/Museum#checklist-for-preparing-a-portfolio-project-for-hr-review)

**Review by polosanya — CHANGES_REQUESTED** [review]
A few more comments that would be great to fix
1. Fix logo position. Also, it would be great for main images to take the whole height
image
image
2. Font doesn't match the design. Also, don't forget to add increasing hover effects
image
image
3. Footer is too big. Also, some details from the design are missing
image
image
4. Fix it
image

**Review by qoa11a — CHANGES_REQUESTED** [review]
Looks like you forgot to deploy your changes. Please, deploy them and re-request the review.

**Review by anstsot — CHANGES_REQUESTED** [review]
It’s almost done! Let’s improve a little
1. Fix the footer according to design
image

2. slider isn't working
image

3. fix mobile version
image

**Comment by Hanna-Balabukha** [comment]
I haven't learned yet how to do a slider.

**Review by anstsot — CHANGES_REQUESTED** [review]
It's almost done
1. Center the logo on mobile
image

2. slider isn't working
image

3. fix the logo position. and facebook icon on hover
image

**Comment by Hanna-Balabukha** [comment]
haven't yet learned how to do a slider

**Review by loralevitska — CHANGES_REQUESTED** [review]
Keep up the good work! Some comments to fix:

- image increase is too big. Create div wrapper for each image and add to this div `overflow:hidden`
image
- text inside the button should be in the center and check your main image according design for tablet mode
image
- fix footer according design 
image

Regarding the slider, there are various libraries that will help you easily make a slider from several pictures. Google it, and if it doesn't work, ask in the chat. It is also normal if you return to the slider after finish the js module, when you learn more about DOM

**Review by Anastasiia-Svintsova — APPROVED** [review]
I approve it, but please fix the carousel before adding the project to the portfolio

- Would be great to add a nover effect to the menu icon
- The spacing between the dividing line doesn't match the design
image

- The slider doesn't work 😢 You can check the errors in the console. You can fix it after the end of the JS course
image

**Pull request closed without merging**
