### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by yurii-krymskiy**
[DEMO LINK](https://yurii-krymskiy.github.io/Museum/)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Demo link doesnt work, try to fix it or ask for help in fe_chat

**Review by vlad-demchuk — CHANGES_REQUESTED** [review]
1. make the while button clickable place
image

2. form submission shouldn't reload a page (now it leads to 405 error)

**Review by vlad-demchuk — COMMENTED** [review]
3. add hovers to all clickable elements
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Add `cursor: pointer` for all size button, not only text 
image
Add a favicon to page
image
Checklist option 13 not done  - Facebook and Instagram icons in the footer should be clickable and open the museum's social networks in a new tab
Additionally, check all points from the checklist before the next review

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Add a transition-duration for this element
image
This link not working
image
No need to open a new tab when clicking on the phone
image

**Review by mykhalenych — CHANGES_REQUESTED** [review]
1. got 405 after submit
Screenshot 2023-05-15 at 16 33 26

2. disable scroll when menu is open
Screenshot 2023-05-15 at 16 34 47

3. slider isn't working
Screenshot 2023-05-15 at 16 35 53

**Pull request closed without merging**
